export const AuthActionTypes = {
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAIL:'REGISTER_FAIL',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    USER_LOADED:'USER_LOADED',
    AUTH_ERROR:'AUTH_ERROR',
    LOGOUT:'LOGOUT',
    AUTH_USER:'AUTH_USER',
    CHECKOUT_CREATE_USER:'CHECKOUT_CREATE_USER',
    CHECKOUT_UPDATE_USER:'CHECKOUT_UPDATE_USER',
    UPDATE_PASSWORD:'UPDATE_PASSWORD'
}