export const AuthActionTypes = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  USER_LOADED: 'USER_LOADED',

  AUTH_USER: 'AUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',

  CHECKOUT_UPDATE_USER: 'CHECKOUT_UPDATE_USER',

  USER_CREATE: 'USER_CREATE',
  USER_CREATE_FAIL: 'USER_CREATE_FAIL',
  USER_UPDATE: 'USER_UPDATE',
  USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',

  PASSWORD_UPDATE: 'PASSWORD_UPDATE',
  PASSWORD_UPDATE_FAIL: 'PASSWORD_UPDATE_FAIL',

  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
}
