export const CategoryActionTypes = {
    GET_CATEGORY:'GET_CATEGORY',
    GET_CATEGORY_FAIL:'GET_CATEGORY_FAIL',
    GET_CATEGORIES:'GET_CATEGORIES',
    GET_CATEGORIES_FAIL:'GET_CATEGORIES_FAIL',
    ADD_CATEGORY:'ADD_CATEGORY',
    ADD_FAIL:'ADD_FAIL',
    UPDATE:'UPDATE',
    UPDATE_FAIL:'UPDATE_FAIL',
    DELETE:'DELETE',
    DELETE_FAIL:'DELETE_FAIL',
    CLEAR_ERRORS:'CLEAR_ERRORS',
}