export const OrderActionTypes = {
    ADD_ORDER:'ADD_ORDER',
    GET_ALL_ORDER:'GET_ALL_ORDER',
    GET_SINGLE_ORDER:'GET_SINGLE_ORDER',
    GET_PENDING_ORDERS:'GET_PENDING_ORDER',
    GET_PROCESSED_ORDERS:'GET_PROCESSED_ORDERS',
    GET_CANCELED_ORDERS:'GET_CANCELED_ORDERS',
    GET_DASHBOARD_ADMIN:'GET_DASHBOARD_ADMIN',
    SEARCH_CHARACTER:'SEARCH_CHARACTER',
    GET_ORDER_HISTORY:'GET_ORDER_HISTORY',
    GET_PAYPAL_SCRIPT:'GET_PAYPAL_SCRIPT',
    CLEAN_ORDER:'CLEAN_ORDER'
}