export const CollectionActionTypes = {
    GET_COLLECTION:'GET_COLLECTION',
    GET_COLLECTIONS:'GET_COLLECTIONS',
    ADD_COLLECTION:'ADD_COLLECTION',
    ADD_FAIL:'ADD_FAIL',
    UPDATE_COLLECTION:'UPDATE_COLLECTION',
    DELETE_COLLECTION:'DELETE_COLLECTION',
    ERROR_COLLECTION:'ERROR_COLLECTION'
}