export const ProductActionTypes = {
    GET_COLLECTION_SUCCESS:'GET_COLLECTION_SUCCESS',
    GET_COLLECTION_FAIL:'GET_COLLECTION_FAIL',
    GET_COLLECTIONS_SUCCESS:'GET_COLLECTIONS_SUCCESS',
    GET_COLLECTIONS_FAIL:'GET_COLLECTIONS_FAIL',
    ADD_SUCCESS:'ADD_SUCCESS',
    ADD_FAIL:'ADD_FAIL',
    UPDATE_SUCCESS:'UPDATE_SUCCESS',
    UPDATE_FAIL:'UPDATE_FAIL',
    DELETE_SUCCESS:'DELETE_SUCCESS',
    DELETE_FAIL:'DELETE_FAIL',
    CLEAR_ERRORS:'CLEAR_ERRORS',
}