export const ProductActionTypes = {
    GET_PRODUCT_TO_HOME:'GET_PRODUCT_TO_HOME',
    GET_PRODUCT_DETAIL:'GET_PRODUCT_DETAIL',
    CLEAR_PRODUCT_DETAIL:'CLEAR_PRODUCT_DETAIL',
    GET_PRODUCT_FAIL:'GET_PRODUCT_FAIL',
    GET_PRODUCTS_SUCCESS:'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL:'GET_PRODUCTS_FAIL',
    ADD_SUCCESS:'ADD_SUCCESS',
    UPDATE_SUCCESS:'UPDATE_SUCCESS',
    UPDATE_FAIL:'UPDATE_FAIL',
    DELETE_SUCCESS:'DELETE_SUCCESS',
    GET_CATEGORIES:'GET_CATEGORIES',
    GET_COLLECTIONS:'GET_COLLECTIONS',
    GET_PRODUCTS_TO_SHOP:'GET_PRODUCTS_TO_SHOP',
    ADD_PRODUCT:'ADD_PRODUCT',
    ERROR_PRODUCT:'ERROR_PRODUCT'
}